name: Notificar modificaci贸n de c贸digo

on:
  push:
    paths:
      - '**.py'

jobs:
  notify-codigo:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar correo
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.CORREO }}
          password: ${{ secrets.CONTRASENA }}
          subject: " C贸digo modificado en Axanet"
          to: "arge.d.17@gmail.com"
          from: "Sistema de Gesti贸n"
          body: |
            Se ha realizado una modificaci贸n en el c贸digo fuente.
            Revisa los cambios en GitHub.
