name: Notificaci贸n servicio nuevo

on:
  push:
    paths:
      - 'Directorio/**/servicios.txt'  # Se activa SOLO cuando editas o creas un servicios.txt
  workflow_dispatch:                  # Mantienes el bot贸n manual por si acaso

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v3

      - name: Enviar correo
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.CORREO }}
          password: ${{ secrets.CONTRASENA }}
          subject: " Servicio Actualizado en Axanet"
          to: "arge.d.17@gmail.com"
          from: "Sistema de Gesti贸n"
          body: |
            Se ha registrado una actualizaci贸n en el archivo de servicios.
            
            Puedes revisar los detalles del nuevo servicio entrando a tu repositorio en GitHub.
