name: Solicitar nuevas funciones

on:
  workflow_dispatch

jobs:
  solicitar-funcion:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar correo
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.CORREO }}
          password: ${{ secrets.CONTRASENA }}
          subject: " Solicitud de nueva funci贸n"
          to: "arge.d.17@gmail.com"
          from: "Sistema de Gesti贸n"
          body: |
            Se ha solicitado una nueva funci贸n para la aplicaci贸n.
            Documenta y planifica su desarrollo.
